name: Deploy Canvas Changes to GitHub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync_canvas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"

      - name: Pull Canvas Changes and Push to GitHub
        run: |
          git pull origin main || true
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "Auto-sync from Canvas"
            git push origin main
          else
            echo "No changes detected, skipping commit."
          fi
